import { AJAX_CALL_SUCCESS_SUFFIX } from './ajaxStatusActionTypes';

export const LOAD_COURSES_SUCCESS = "LOAD_COURSES" + AJAX_CALL_SUCCESS_SUFFIX;
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE" + AJAX_CALL_SUCCESS_SUFFIX;
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE" + AJAX_CALL_SUCCESS_SUFFIX;

export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS" + AJAX_CALL_SUCCESS_SUFFIX;
